language: ruby
node_js: - "8.10"
rvm: -2.5.1
install: - gem install jekyll bundler
         - gem install html-proofer
before_script: - bundle install
script: - bundle exec jekyll build
        - bundle exec htmlproofer ./_site
branches: only: - master
after_success: - echo "Build successful"