language: ruby
node_js:
    - "8.10"
rvm: 
    - 2.5.1
install:
    - gem install jekyll bundler
    - gem install html-proofer
    - npm install -g firebase-tools
before_script:
    - bundle install
script:
    - bundle exec jekyll build
    #- bundle exec htmlproofer ./_site --disable-external
branches:
    only:
        - release
        - Develop
        - master
after_success:
    - echo "Build was successful"
    #- firebase deploy --token "$FIREBASE_TOKEN"
deploy:
    provider: firebase
    skip_cleanup: true
    token: 
        env: $FIREBASE_TOKEN
    on:
        branch: release


